version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: myapp_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "0.0.0.0:5433:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    external: true                               # <--- ADD THIS
    name:  inventory-rental-backend_postgres_data        # <--- ADD THIS (Use the exact name from Docker Desktop)