# Generated by Django 5.2.7 on 2025-10-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_user_name_user_phone_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('receiver', 'Receiver'), ('base', 'Base'), ('rover', 'Rover'), ('accessory', 'Accessory')], default='receiver', max_length=50),
        ),
        migrations.AddField(
            model_name='tool',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('maintenance', 'Maintenance'), ('disabled', 'Disabled'), ('sold', 'Sold')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='tool',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
