# Generated by Django 5.2.7 on 2025-10-12 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment", models.CharField(max_length=255)),
                ("cost_sold", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_sold", models.DateField()),
                ("invoice_number", models.CharField(max_length=100, unique=True)),
                (
                    "payment_plan",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"role": "customer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
