# Generated by Django 5.2.7 on 2025-10-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_sale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("equipment", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "cost_sold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("date_sold", models.DateField(blank=True, null=True)),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payment_plan",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_activated", models.BooleanField(default=False)),
            ],
        ),
    ]
