# Generated by Django 5.2.7 on 2025-10-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_tool_category_tool_supplier_alter_tool_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('Receiver', 'Receiver'), ('Base', 'Base'), ('Rover', 'Rover'), ('Accessory', 'Accessory'), ('Power Tool', 'Power Tool'), ('Measuring', 'Measuring'), ('Safety Gear', 'Safety Gear'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Maintenance'), ('disabled', 'Disabled'), ('sold', 'Sold')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='tool',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tool',
            name='supplier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('customer', 'Customer')], default='staff', max_length=20),
        ),
    ]
