# Generated by Django 5.2.7 on 2025-10-12 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="cost_sold",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="date_sold",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="expiry_date",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="invoice_number",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="payment_plan",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="state",
        ),
        migrations.AddField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
