# Generated by Django 5.2.7 on 2025-10-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_sale_staff_alter_sale_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='status',
        ),
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('Receiver', 'Receiver'), ('Acessory', 'Acessory'), ('Total Station', 'Total Station'), ('Level', 'Level'), ('Drones', 'Drones'), ('EcoSounder', 'EcoSounder'), ('Laser Scanner', 'Laser Scanner'), ('Other', 'Other')], max_length=50),
        ),
    ]
