# Generated by Django 5.2.7 on 2025-10-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_customer_cost_sold_remove_customer_date_sold_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='price_per_day',
            new_name='cost',
        ),
    ]
