# Generated by Django 5.2.7 on 2025-10-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_tool_date_added_tool_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='serials',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('Receiver', 'Receiver'), ('Accessory', 'Accessory'), ('Total Station', 'Total Station'), ('Level', 'Level'), ('Drones', 'Drones'), ('EcoSounder', 'EcoSounder'), ('Laser Scanner', 'Laser Scanner'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tool',
            name='supplier',
            field=models.CharField(blank=True, choices=[('COMNAV TECHNOLOGY', 'COMNAV TECHNOLOGY'), ('GINTEC', 'GINTEC'), ('AMAZE MULTILINKS', 'AMAZE MULTILINKS'), ('HARRYMORE', 'HARRYMORE'), ('LEICA GHANA', 'LEICA GHANA'), ('QUEST', 'QUEST'), ('ADA SWISS-SURVEY', 'ADA SWISS-SURVEY'), ('IVY ZENGYU', 'IVY ZENGYU'), ('FOIF', 'FOIF'), ('SANGRAO HAODI', 'SANGRAO HAODI'), ('OTHER', 'OTHER')], max_length=100),
        ),
    ]
