# Generated by Django 5.2.7 on 2025-10-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_tool_serials_alter_tool_category_alter_tool_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='rental',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
