# Generated by Django 5.2.7 on 2026-03-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_sale_date_sold_alter_sale_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tax Amount (7.5%)'),
        ),
    ]
