# Generated by Django 5.2.7 on 2025-10-22 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='inventory.supplier'),
        ),
    ]
