# Generated by Django 5.2.7 on 2026-03-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_sale_tax_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='staff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
