# Generated by Django 5.2.7 on 2026-03-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_sale_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('installment', 'Installment'), ('failed', 'Failed'), ('overdue', 'Overdue')], db_index=True, default='pending', max_length=20),
        ),
    ]
