# Generated by Django 5.2.7 on 2025-10-24 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_tool_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='receiver_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='inventory.receivertype', verbose_name='Receiver Type (for Receiver category only)'),
        ),
    ]
