# Generated by Django 5.2.7 on 2026-03-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_sale_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='sale',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Final Due Date'),
        ),
    ]
