# Generated by Django 5.2.7 on 2025-10-24 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_tool_receiver_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.CharField(choices=[('Receiver', 'Receiver'), ('Accessory', 'Accessory'), ('Total Station', 'Total Station'), ('Level', 'Level'), ('Drones', 'Drones'), ('EcoSounder', 'EcoSounder'), ('Laser Scanner', 'Laser Scanner'), ('Other', 'Other')], default='Receiver', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tool',
            name='receiver_type',
        ),
        migrations.AddField(
            model_name='tool',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='inventory.equipmenttype', verbose_name='Equipment Type'),
        ),
        migrations.DeleteModel(
            name='ReceiverType',
        ),
    ]
