# Generated by Django 5.2.7 on 2026-04-01 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_sale_expiry_date_sale_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('overdue', 'Overdue'), ('fully-paid', 'Fully Paid')], default='ongoing', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
