# Generated by Django 5.2.7 on 2025-10-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_equipmenttype_remove_tool_receiver_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='equipmenttype',
            index=models.Index(fields=['invoice_number'], name='inventory_e_invoice_b97a60_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmenttype',
            index=models.Index(fields=['category'], name='inventory_e_categor_fbecb7_idx'),
        ),
    ]
