# Generated by Django 5.2.7 on 2026-04-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_customer_status_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
    ]
