# Generated by Django 5.2.7 on 2026-04-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_quotation_quotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='account_name',
            field=models.CharField(default='OTIC GEOSYSTEMS LTD', max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='account_number',
            field=models.CharField(default='1015175251', max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='bank_name',
            field=models.CharField(default='Zenith Bank', max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='footer_note',
            field=models.TextField(default='This is a quotation only and does not constitute a final invoice.'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tin_number',
            field=models.CharField(default='31413107-0001', max_length=50),
        ),
    ]
