# Generated by Django 5.2.7 on 2025-10-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_sale_customer_remove_sale_equipment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='cost_sold',
            new_name='total_cost',
        ),
    ]
