# Generated by Django 5.2.7 on 2025-10-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_rename_cost_sold_sale_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
    ]
