# Generated by Django 5.2.7 on 2025-10-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_tool_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='available_serials',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tool',
            name='sold_serials',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
