# Generated by Django 5.2.7 on 2025-10-29 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_saleitem_serial_number_tool_available_serials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_sold',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
