# Generated by Django 5.2.7 on 2025-10-30 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_sale_date_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_sold',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
