# Generated by Django 5.2.7 on 2025-10-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_sale_date_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='amount_left',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount Left'),
        ),
        migrations.AddField(
            model_name='customer',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount Paid'),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_last_paid',
            field=models.DateField(blank=True, null=True, verbose_name='Date Last Paid'),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_next_installment',
            field=models.DateField(blank=True, null=True, verbose_name='Next Installment Date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='progress',
            field=models.IntegerField(default=0, help_text='Percentage of total amount paid', verbose_name='Payment Progress (%)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('on-track', 'On Track'), ('due-soon', 'Due Soon'), ('overdue', 'Overdue'), ('fully-paid', 'Fully Paid')], default='on-track', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Selling Price'),
        ),
    ]
