# Generated by Django 5.2.7 on 2025-10-31 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_customer_amount_left_customer_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_sold',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
