# Generated by Django 5.2.7 on 2025-10-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_sale_date_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='import_invoice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='assigned_tool_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
